// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `prisma dev` runs a dedicated shadow-db server alongside the main one
    // (see `npx prisma dev ls`) — pointing at it directly avoids `migrate dev`
    // trying to provision its own shadow database on the main server, which
    // this lightweight local server doesn't support (P1017).
    shadowDatabaseUrl: "postgres://postgres:postgres@localhost:51215/template1?sslmode=disable",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
